### PR TITLE
fix(types): make value a generic type, not a ValueType

### PR DESCRIPTION
**Pull request by mlecoq**
Hi, 

Currently values have ValueType type (boolean, number or string). It leads to have to deal with boolean or number when string are used as values for example.

The goal is this PR is to set ValueType as generic

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Awesome, I love the idea
This PR is really "noisy" though, it contains all sorts of unrelated changes bunched in to one commit.
Most of the changes I would call "lint", they are non-functional changes of single quotes to double qoutes or spacing, all of which add up to 57 total line changes when I think the functional change is really like 4?
Makes it hard to review
Can you post a PR that changes just the things you need to change? Or at least split the lint and the functional change in to separate commits, so nothing is missed in review among the noise?

**Comment by mlecoq** [comment]
@mikehardy  done !

**Review by mikehardy — COMMENTED** [review]
okay - much easier to see the changes now, thank you!
can you explain to me - as a big fan of typescript but someone not good at generating type definitions - is this a breaking change for any existing users, or is it just making the return types easier to handle as they come back from item selection?
I should just download the diff and check it but I'm really short of time at the moment, sorry

**Comment by mlecoq** [comment]
currently with the following code 

```typescript
const App = () => {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState<string | null>(null);
  const [items, setItems] = useState([
    {label: 'Apple', value: 'apple'},
    {label: 'Banana', value: 'banana'},
  ]);

  return (
    <DropDownPicker
      open={open}
      value={value}
      items={items}
      setOpen={setOpen}
      setValue={setValue}
      setItems={setItems}
    />
  );
};
```

I have a typescript issue on `setValue` : 

```
 Type 'SetStateAction<ValueType | null>' is not assignable to type 'SetStateAction<string | null>'.
      Type 'number' is not assignable to type 'SetStateAction<string | null>'
```

`setValue` of `DropDownPicker` has the following definition `Dispatch<SetStateAction<ValueType | null>>`, so setValue can provide as value a `number` or a `boolean` but mine `setValue` from `useState` only accepts `string` or `null`

One workaround is casting 

```typescript
 setValue={setValue as Dispatch<SetStateAction<ValueType | null>>}
```

The benefit of using a generic is that `items`, `setItems`, `value` and `setValue` are consistent

I don't think it's a breaking change since you can still use value typed as `ValueType`

```typescript
const App = () => {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState<ValueType | null>(null);
  const [items, setItems] = useState([
    {label: 'Apple', value: 'apple'},
    {label: 'Banana', value: 'banana'},
    {label: 'Cherry', value: 3},
    {label: 'Durian', value: false},
  ]);

  return (
    <DropDownPicker
      open={open}
      value={value}
      items={items}
      setOpen={setOpen}
      setValue={setValue}
      setItems={setItems}
    />
  );
};
```

**Review by mikehardy — APPROVED** [review]
Thanks for the explanation, I really appreciate it.
I'll do my best to edit the PR title so it works well as a self-contained release note, if you see anything that could be improved about my edit please let me know
Otherwise, @hossein-zare I think this improves the types, looks okay for a merge?

**Comment by hossein-zare** [comment]
Thank you @mlecoq @mikehardy 

No idea why i don't get notifications.

One of desired improvements.
Mergeable if you think it's ready.

**Pull request merged**
