### PR TITLE
feat:  add italian translation

### PR DESCRIPTION
**Pull request by Angelk90**
Hi @hossein-zare , could you check if line 47 of the `src/translations/index.js` control was written correctly, I had to improvise a little.

### CODE REVIEW

**Comment by hossein-zare** [comment]
Hi,

Thank you for the PR.

> could you check if line 47 of the src/translations/index.js control was written correctly, I had to improvise a little.

No, `{count}` is replaced using the [`String.prototype.replace()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) method so you can't do `{count} === 1`.

https://github.com/hossein-zare/react-native-dropdown-picker/blob/71c166b68d3d8fc0ac8356eb487c091c0aa1253c/src/components/Picker.js#L592

Please follow the English translation.
https://github.com/hossein-zare/react-native-dropdown-picker/blob/e37d8696f5010d45c0a0998a787fe675d87fdb24/src/translations/index.js#L5

Your idea of conditionating translations is really good, If you don't mind, Please create a new issue for that (Feature Request).
That won't be possible but alternative solutions will be introduced.

**Comment by Angelk90** [comment]
@hossein-zare : The problem if I had to follow the English translation would not be very correct in Italian, it is difficult to explain.
I can do it anyway, we will see to fix it in the future.

**Comment by hossein-zare** [comment]
Okay, We had the same problem with the Russian translation.

**Comment by Angelk90** [comment]
@hossein-zare : Ok, I don't really like it as a linguistic form, but I tried to follow the Spanish example.

**Comment by hossein-zare** [comment]
@Angelk90
I'm going to mark your PR as pending and improve the translation system.
Later i'll ask you to update your translation.

Thank you.

**Comment by hossein-zare** [comment]
@Angelk90 

Is it ok now?

**Comment by Angelk90** [comment]
@hossein-zare : Updated.

**Pull request merged**
