### PR TITLE
added keyboard logic

### PR DESCRIPTION
**Pull request by zaiisao**
this addresses the issue I wrote in https://github.com/hossein-zare/react-native-dropdown-picker/issues/234

### CODE REVIEW

**Comment by hossein-zare** [comment]
Hello,

Thank you for the PR.
I'll merge it soon.

**Comment by zaiisao** [comment]
@hossein-zare If you plan to merge it, would you like me to update the readme or is that something you usually do?

**Comment by zaiisao** [comment]
Made update so that the keyboard listeners are removed when unmounting.

**Comment by hossein-zare** [comment]
@zaiisao What props are added to the package?

**Comment by zaiisao** [comment]
I did not add any props.

**Pull request merged**
