### PR TITLE
feat(arrow-position): arrowIconPosition property addition

### PR DESCRIPTION
**Pull request by thegdznet**
Hi and many thanks for Your work.

For the project I'm working on, I added `arrowIconPosition` to be able to place it to the left.

Fell free to accept or reject this PR.

Guillaume.

PS:  List animation is coming...

### CODE REVIEW

**Review by mikehardy — COMMENTED** [review]
this is more of a thought-level comment, I have noticed that a lot of RTL-aware components, and react-native itself, has attempted to use "start" and "end" for positioning vs the non-RTL-aware words "left" or "right", and then the components try to do RTL correctly for the component user by looking into the I18NManager component to check RTL, then placing it correctly on the right or left.

I wonder if that's something worthwhile to do here? If not, then to use these LEFT/RIGHT specifiers in an RTL-aware manner, every single component user will have to examine I18N RTL status on their own and be trusted to handle it...

**Comment by thegdznet** [comment]
I can change LEFT/RIGHT to START/END if You prefer.

**Comment by mikehardy** [comment]
I think that's a real question of taste with @hossein-zare - I personally would remove it and make it RTL aware but I also haven't checked what the performance impact of that would be, or even if that's really wanted 🤷 - but I'm curious what Hossein thinks

**Comment by hossein-zare** [comment]
The wrapper `TouchableOpacity` is RTL aware so `START` and `END` are ok as far as i know.
The themes should also be updated as @mikehardy noted here:
> I have noticed that a lot of RTL-aware components, and react-native itself, has attempted to use "start" and "end" for positioning vs the non-RTL-aware words "left" or "right"...

I'll merge your PR after getting things done.

https://github.com/hossein-zare/react-native-dropdown-picker/blob/ae12571c27419f623f93ee1d0327c84ff2e78f3a/src/components/Picker.js#L727-L733

https://github.com/hossein-zare/react-native-dropdown-picker/blob/ae12571c27419f623f93ee1d0327c84ff2e78f3a/src/components/Picker.js#L1739

**Comment by Angelk90** [comment]
@thegdznet : What do you mean by list animation?

**Pull request closed without merging**
