### PR TITLE
chore: added templates etc to enable contributions

### PR DESCRIPTION
**Pull request by taeh98**
Hey @hossein-zare, I hope you're doing well!

I've made some stuff that will help people contribute to the repo in the future:
- a CONTRIBUTING.md guidance file to improve the quality of contributions and help people who want to contribute to know how to do so
- a pull request template to standardise them and make them easier to review
- issue templates to improve the quality of issues => improve maintainers' ability to handle them
- some other minor things too

When you get time, please could you take a look and let me know what you think of the general idea and what I've made? Thanks :)

### CODE REVIEW

**Comment by hossein-zare** [comment]
Hey,

I appreciate the changes.
Some of the templates are complicated and confusing as I personally don't provide all the information or answer the questions asked when reporting a bug or I may give up, I'm lazy 😕.
Please keep them as simple as possible or Submit them in a separate PR, I'll edit them later.

Thanks. 🙂

**Comment by taeh98** [comment]
> Hey,
> 
> I appreciate the changes. Some of the templates are complicated and confusing as I personally don't provide all the information or answer the questions asked when reporting a bug or I may give up, I'm lazy 😕. Please keep them as simple as possible or Submit them in a separate PR, I'll edit them later.
> 
> Thanks. 🙂

Hey @hossein-zare

I guess it's a balance. At the moment, a lot of the issues are low quality, without all the info needed to follow them up properly. On the other hand, yeah, it might dissuade people from making an issue if they have to fill out a lot of stuff. At the same time, if someone really does have a bug/feature request/problem, I think they will be motivated enough to fill them out (maybe even lazily, missing or deleting some stuff).

I'll have another look at some point and see if I can strip anything back from them. In the meantime, I merged in some unrelated but straightforward stuff, so it's just the templates and contributing file in this PR now, making it easier to review.

Thanks!

**Comment by taeh98** [comment]
Going to make separate PRs and branches for issue templates and the PR template.

**Comment by taeh98** [comment]
New PR for issue templates: https://github.com/hossein-zare/react-native-dropdown-picker/pull/765

New PR for pull request template: https://github.com/hossein-zare/react-native-dropdown-picker/pull/764

**Pull request closed without merging**
