### PR TITLE
remove unneeded error; add license badge and usage info to readme

### PR DESCRIPTION
**Pull request by taeh98**
- remove unneeded error when value prop != memoryRef.value.current at the start of the item press callback; I thought they should remain consistent but found in testing dropdowns work even when they aren't
- add licence badge and link to usage info to readme

### CODE REVIEW

**Comment by hossein-zare** [comment]
Hey @taeh98 
Where can we talk about this issue, https://github.com/hossein-zare/react-native-dropdown-picker/issues/668

**Comment by taeh98** [comment]
> Hey @taeh98 Where can we talk about this issue, #668

Hi @hossein-zare, hope you're good. I'm currently working on #641 since I had the same issue. I just found the docs on usage with class components, so I'm trying to see if following them solves the issue for me right now.

What needs to happen with #668? Just making the same changes that guy did in a PR?

**Comment by hossein-zare** [comment]
Thanks.

I've already fixed the bug (not sure) months ago.
Could you please apply @jobrdelivery 's solution to your project (not the repository) and tell me if it's bug-free and works as expected? You can also install `5.4.7-beta.1` instead.

**Comment by taeh98** [comment]
> Thanks.
> 
> I've already fixed the bug (not sure) months ago. Could you please apply @jobrdelivery 's solution to your project (not the repository) and tell me if it's bug-free and works as expected? You can also install `5.4.7-beta.1` instead.

No problem!

You fixed #641 months ago? I'm just trying to make it work per the docs at the moment.

And yes, I'll test it out at some point and let you know - I have to get my project working first anyway because it broke from v4 to v5 with #641.

**Comment by hossein-zare** [comment]
I fixed #668
Let me know if it's buggy with class components.

**Pull request merged**
