### PR TITLE
🐛 FIX: reset values on reset()

### PR DESCRIPTION
**Pull request by hkar19**
🐛 FIX: reset values on reset()

### CODE REVIEW

**Comment by hkar19** [comment]
#198

**Comment by hkar19** [comment]
https://github.com/hossein-zare/react-native-dropdown-picker/issues/198#issuecomment-771214297

**Comment by andreszuluaga-wolox** [comment]
this solution worked for me

**Comment by hkar19** [comment]
oh really? have you tried @hossein-zare solution first?

for me this solution works but so does his solution without merging this.

IMO, on reset the component should reset its values as well, hence my solution. I dunno why @hossein-zare solution works.

**Comment by andreszuluaga-wolox** [comment]
yes, I try the solution of @hossein-zare, but not worked for me, and apply your solution and fix the problem

**Comment by hossein-zare** [comment]
@andreszuluaga-wolox Please create an issue, Add your code.

**Pull request closed without merging**
